# Generated by Django 3.1 on 2020-08-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('HR', 'Hero'), ('SD', 'Side')], default='HR', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('ZI', 'Zima'), ('PR', 'Prolece'), ('LT', 'Leto'), ('JS', 'Jesen')], default='LT', max_length=2),
        ),
    ]
